---
- name: Update debian packages
  apt: update_cache=true
  notify: Upgrade debian packages

- name: Install required packages
  apt: state=present name={{ item }}
  with_items:
    - sudo
    - postgresql

- name: Make sure ssh agent forwarding works
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: SSH_AUTH_SOCK
    line: Defaults env_keep+=SSH_AUTH_SOCK
