language: python
python:
  - "3.5"
addons:
  - postgresql: "9.3"
services:
  - elasticsearch
before_install:
  - sudo apt-get install -qq zlib1g-dev
  - npm install -g grunt-cli
install:
  - pip install -r requirements/test.txt
  - npm install -g cssmin uglify-js
  - npm install -g casperjs
  - cd src
  - npm install
before_script:
  - psql -c "CREATE USER phase WITH SUPERUSER PASSWORD 'phase';" -U postgres
  - psql -c 'CREATE DATABASE phase_test;' -U postgres
script:
  - export DJANGO_SETTINGS_MODULE=core.settings.test
  - grunt
  - flake8 --exclude=migrations,docs,urls.py,bootstrap/bootstrap-src --ignore=E501 .
  - python manage.py collectstatic --noinput
  - coverage run --source='.' manage.py test --noinput
after_success:
  - coveralls
notifications:
  - recipients:
    - thibault@jouannic.fr
  - on_success: change
  - on_failure: always
