---
- name: Pull / clone main project repo
  git:
    repo: "{{ project_repo }}"
    dest: "{{ project_root }}"
    version: "{{ project_version }}"
    accept_hostkey: yes

- name: Install additional document apps
  git:
    repo: "{{ item.repo }}"
    dest: "{{ install_root }}/{{ item.name }}"
    accept_hostkey: yes
    version: "{{ project_version }}"
  with_items: "{{ document_apps }}"
